name: perl
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
  create:
jobs:
  notify:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    steps:
      - uses: PDLPorters/devops/github-actions/irc-notifications@master
        with:
          target-notifications: true
  ci:
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    needs: notify
    env:
      PGPLOT_DEV: /NULL
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11]
        perl-version: ['5.10', '5.14', '5.20', '5.30']
        install-pgplot: [ true, false ]
        # make macos-11 be part of the matrix so it gets the
        # install-pgplot parameters, but only want it to test
        # perl-version = 5.30. so, remove all of macos-11 here, and
        # then include the match against perl-version below
        exclude:
          - os: macos-11
        include:
          - perl-version: '5.30'
            os: ubuntu-latest
            release-test: true
            coverage: true
          # Disable windows
          # NOTE pgplot does not yet have a build for windows
          #- perl-version: '5.30'
          #  os: windows-latest
          - perl-version: '5.30'
            os: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: 'ci-dist: target-setup-perl'
        uses: PDLPorters/devops/github-actions/ci-dist@master
        with:
          target-setup-perl: true
          perl-version: ${{ matrix.perl-version }}
      - name: Install gfortran
        uses: PDLPorters/devops/github-actions/install-gfortran@master
      - name: Install PGPLOT
        uses: PDLPorters/devops/github-actions/install-pgplot@master
        if: matrix.install-pgplot
      - name: 'ci-dist: target-all'
        uses: PDLPorters/devops/github-actions/ci-dist@master
        with:
          target-setup-perl: false
          target-install-dist-perl-deps: true
          dist-perl-deps-configure: Alien::Base::Wrapper Alien::PGPLOT
          target-test-release-testing: true
          target-test: true
          test-enable-release-testing: ${{ matrix.release-test }}
          test-enable-coverage: ${{ matrix.coverage }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-status:
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ always() }}
    needs: [ 'ci' ]
    steps:
      - uses: PDLPorters/devops/github-actions/irc-notifications@master
        with:
          target-build-status: true
          needs: ${{ toJSON(needs) }}
